import { Navigate,Route,Routes } from "react-router-dom";
import { ProtectedRoute,RoleHome,LegacyDashboardRedirect,staffRoles } from "./RouteGuards";
import LoginPage from "../pages/LoginPage"; import RegisterPage from "../pages/RegisterPage";
import AdminPage from "../features/admin/AdminPage"; import AdminDashboardPage from "../pages/AdminDashboardPage"; import AdminReportsPage from "../pages/AdminReportsPage"; import AdminAuditPage from "../pages/AdminAuditPage";
import StaffDashboardPage from "../pages/StaffDashboardPage"; import PatientDashboardPage from "../features/patients/PatientDashboardPage"; import PatientProfilePage from "../pages/PatientProfilePage"; import PatientDataPage from "../pages/PatientDataPage";
import AdminLayout from "../layouts/AdminLayout"; import StaffLayout from "../layouts/StaffLayout"; import PatientLayout from "../layouts/PatientLayout";
import PatientPage from "../features/patients/PatientPage"; import PatientClinicalPage from "../features/patients/PatientClinicalPage"; import PatientAppointmentsPage from "../features/patients/PatientAppointmentsPage";
import AppointmentPage from "../features/appointments/AppointmentPage"; import BillingPage from "../features/billing/BillingPage"; import DoctorPage from "../features/doctors/DoctorPage"; import PharmacyPage from "../features/pharmacy/PharmacyPage"; import LaboratoryPage from "../features/laboratory/LaboratoryPage"; import ClinicalCarePage from "../features/clinical/ClinicalCarePage"; import NotificationsPage from "../features/notifications/NotificationsPage";
export default function AppRoutes(){return <Routes><Route path="/" element={<RoleHome/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/dashboard" element={<ProtectedRoute><LegacyDashboardRedirect/></ProtectedRoute>}/><Route path="/admin" element={<ProtectedRoute allowedRoles={["admin"]}><AdminLayout/></ProtectedRoute>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<AdminDashboardPage/>}/><Route path="users" element={<AdminPage/>}/><Route path="patients" element={<PatientPage/>}/><Route path="appointments" element={<AppointmentPage/>}/><Route path="doctors" element={<DoctorPage/>}/><Route path="billing" element={<BillingPage/>}/><Route path="pharmacy" element={<PharmacyPage/>}/><Route path="laboratory" element={<LaboratoryPage/>}/><Route path="clinical" element={<ClinicalCarePage/>}/><Route path="reports" element={<AdminReportsPage/>}/><Route path="audit" element={<AdminAuditPage/>}/></Route><Route path="/staff" element={<ProtectedRoute allowedRoles={staffRoles}><StaffLayout/></ProtectedRoute>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<StaffDashboardPage/>}/><Route path="patients" element={<ProtectedRoute allowedRoles={["doctor","nurse","receptionist"]}><PatientPage/></ProtectedRoute>}/><Route path="appointments" element={<ProtectedRoute allowedRoles={["doctor","nurse","receptionist"]}><AppointmentPage/></ProtectedRoute>}/><Route path="doctors" element={<ProtectedRoute allowedRoles={["doctor","nurse"]}><DoctorPage/></ProtectedRoute>}/><Route path="billing" element={<ProtectedRoute allowedRoles={["accountant"]}><BillingPage/></ProtectedRoute>}/><Route path="pharmacy" element={<ProtectedRoute allowedRoles={["pharmacist","doctor"]}><PharmacyPage/></ProtectedRoute>}/><Route path="laboratory" element={<ProtectedRoute allowedRoles={["laboratory","doctor"]}><LaboratoryPage/></ProtectedRoute>}/><Route path="clinical" element={<ProtectedRoute allowedRoles={["doctor","nurse"]}><ClinicalCarePage/></ProtectedRoute>}</Route><Route path="/patient" element={<ProtectedRoute allowedRoles={["patient"]}><PatientLayout/></ProtectedRoute>}><Route index element={<Navigate to="dashboard" replace/>}/><Route path="dashboard" element={<PatientDashboardPage/>}/><Route path="profile" element={<PatientProfilePage/>}/><Route path="appointments" element={<PatientAppointmentsPage/>}/><Route path="clinical" element={<PatientClinicalPage/>}/><Route path="notifications" element={<NotificationsPage/>}/><Route path="prescriptions" element={<PatientDataPage type="prescriptions"/>}/><Route path="laboratory" element={<PatientDataPage type="laboratory"/>}/><Route path="billing" element={<PatientDataPage type="billing"/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
